---
title: R class, topics by week
author: Ozan Jaquette and Patricia Martin
date: 
output: 
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
---

# General

## wish list for beamer slides

- smaller font-size; similar to fontsize from Christenson slides
- code in code chunks wraps to next row rather then bleeds off right margin
- reduce horizontal space between line of text and first item of list below that line of text
- when I run a code chunk RMarkdown that includes a print of data, the printout below the chunk looks the way printing data from console looks as opposed to having the df_print: paged style (HTML tables with support for pagination over rows and columns)

## Stuff for students to do before class

1. Install R
1. Install RStudio
1. Install MikTeX
1. Knit following documents in RMarkdown
    - html
    - pdf_document
    - beamer_presentation
1. Watch videos on relative and absolute filepaths
    - the general one
    - the one in R
1. Complete intro to R tutorials
    - which ones

# Alternative approaches

- current
    - class 1: objects
    - class 2: investigating data patterns
        - investigating objects
        - printing data
        - selecting variables
        - sorting data
        - missing values
        - operators
        - filtering data
        - descriptive statistics [cut? move to later week?]
    - class 3:
        - review data structures
        - attributes and augmented vectors
        - factors
        - labeling varoiables
        - pipes
        - creating variables
        - creating variables using mutate
    - class 4: 
        - group_by
        - summarise()
        - combining group_by and summarise()
            - counts
            - means
            - logical vectors
            - na.rm
        - attach aggregate measures to data frame
    - class 5: 
        - EDA for data quality
        - preparing for creation of GPA 
- alternative
    - class 1: objects
    - class 2: 
        - pipes
        - selecting variables
        - sorting data
        - filtering data
        - creating variables
    - class 3
        - group_by and summarise()
    - class 4: factors and investigating data patterns/EDA?4
        - data structures and factors
          - review data structures
          - attributes and augmented vectors
          - factors
          - labeling variables
        - EDA for data quality
    - class 5: review of core stuff?

# Topics by week

## Class 1. Introduction and data types

### Big topics

- Course objectives
    - Broad
    - Specific topics we will learn
    - Stuff you can do in R that we will not learn
- What is R? What can R do?
    - Base R
    - R packages
- Complements to R
    - Rstudio
    - RMarkdown
- Introduction to R
    - Open a dataset and print some observations
    - Objects and assignment
        - R is an object oriented programming language
        - Objects in R
        - Assignment
        - Printing objects
    - Functions and help
        - basic syntax
        - help files
    - Data types
    - Packages
      - installing packages
      - loading packages
    - Filepaths    

What Patricia says:

2.	You might be planning to do this anyway, but I think it would be a good idea to explain what data management is during the first class meeting. Equally important, we should mention who this class is for. What I mean by this is that there may be folks who are experienced with R, but have no clue how to clean data or other folks who have experience with data management, but are new to R, or others who have no experience with either, etc. 
3.	It would also be a good idea to discuss other uses for R during the first class meeting (graphing, mapping, web scraping, etc.) to introduce students to the various uses of R so they could potentially invest in learning more advanced methods in the future. 
4.	I agree that strings require at least two weeks, but I also think we should briefly go over them if we can because they may be needed for the weeks on functions and iterations. 



### Learning objectives

- directories
    - understand difference between absolute and relative filepaths
    - can identify the current working directory
    - change the working directory using absolute filepath
    - change current working directory using relative filepath
- data types
    - Understand the different data types and how they fit into broader categories
    - 

### Data sources

### Reading [after lecture]

### Problem set ideas

### What covered in Stata data mgt course

- lecture 1:
    - course objectives, why important
    - syllabus and logistics
        - core data manipulation skills you should know
        - homework
        - communication with instructor and classmates
        - course etiquette
    - understanding syntax of stata commands
    - executing stata commands
    - where to find resources and help
    - Stata do-files
    - changing directories
    - Stata log-files

### What covered in Christenson class

1. What is data science
1. Course goals
1. Student introductions
1. Course logistics
    - course components
    - course outline
1. Tools for using R
    - what is R; R packages; why R
1. Complementary tools
    - RStudio
    - RMarkdown
1. R basics [review of material from Try R tutorials]
    - creating vectors
    - reading help page
    - indexing (e.g., grab row 3 and column 2)
    - logical expressions
    - Useful functions for data frames

## Class X. Investigating data patterns

### Big topics

- ?directories and filepaths?
- investigating objects
- printing data
- selecting variables
- sorting data
- missing values
- operators
- filtering data
- descriptive statistics [cut? move to later week?]

### Learning objectives

- Select desired observations, based on numeric and character variables
    - skills: operators; filtering; character variables
- Print desired desired variables and desired observations in desired order for a dataset
    - skills: printing; selecting variables; filtering observations; sorting observations
- Explicitly include or exclude missing observations
    - skills: missing values in quant or character variables
- Conduct basic descriptive statistics: one-way and two-way; categorical and continuous
    - skills: 

### Data sources

### Reading [after lecture]

### Problem set ideas

### What covered in Stata data mgt course

- isolating variables
    - lookfor
- Isolating specific observations
    - tabulate command
        - with missing option
        - with numlabel
    - isolating observations using “operators”
    - isolating observations, string variables
    - inlist() function
    - missing values
- sorting and listing observations
    - list command [equivalent to print command]
    - assert command
    - combining _variables with bysort [I think save this topic until by-groups week]
    - combining bysort variables and assert [I think save this topic until by-groups week]
- checking variables and cleaning data [I think save this topic until week on data cleaning]
    - assert to check double data entry
    - checking categorical variables, one-way tabulation
    - checking categorical variables, two-way tabulation
    - checking continuous variables

### What covered in Christenson class

## Class X. Creating variables, factors, labeling variables

### Big topics

- Pipes [DONE]
* Creating variables [DONE]
* class=Factors [DONE]
* class=labelled [or put this in EDA section]
    - labelling variables
    - labelling values


### Learning objectives

* gain intuitive understanding of how "pipes" work
* Create variables that are based on calculations across observations and within rows
* be able to add labels to variables
* be able to add value labels to factor variables
* be able to turn string categorical variables into numeric factor variables

### questions [for Ben/Crystal]

* How to introduce data types and data structures
    - Skinner introduces concept of data types (logical, numeric, character) and data structures (vectors, lists, etc.); 
    - by contrast, Wickham introduces vectors [atomic vectors vs. lists] and then the data types as different types of atomic vectors
        - [LINK TO FIGURE](http://r4ds.had.co.nz/diagrams/data-structures-overview.png)
    - which is correct?
* class vs. type

### Reading [after lecture]

### Data sources

### Problem set ideas

- Create variables and add value labels

### What covered in Stata data mgt course

    
- lecture 4:
    * label variables
        * add variable labels
        * add value labels
            * add num labels to value labels
        * view value labels
        * add notes to variables
    * variable storage type and display format
        * internal storage type
        * display format
    * create variables (part 1)
        * principles of variable creation [e.g., don't change input var]
        * Creating variables using different commands
            * introducing egen
        * other

### What covered in Christenson class

- lecture 4 [manipulating data frames, 1]
    - introduction to dplyr
        - verbs
            - subsetting: filter, select
            - ordering: arrange
            - transforming: mutate, summarize, group_by
    - subsetting
        - filtering
        - select
        - sample_n, sample_frac, slice
    - ordering
        - arrange
    - transform
        - mutate
    
- lecture 5 [manipulating data frames, 1]
    - loading data [brief]
    - transform data
        - mutate to create new variables [using the pipe]
        - group_by 
        - summarize (aggregate and collapse)
    - presenting summary statistics
        - creating tables
            - using summarize() function
        - plot and aggregate data

## Class X. Processing across rows; exploratory data analysis for data quality

### Big topics

  - Processing across rows with summarize() and group by


### Learning objectives

### Order of lecture

1. Processing across obs
    1. introduce group_by() and summarize()
        - Introduce each command on its own and then together
        - ? INTRODUCE SUMMARISE() OR GROUP_BY() FIRST?
        - Common functions to use with summarize (e.g., n _, mean, median, sum, nth)
    1. How missing values handled by summarize
be a missing value. Fortunately, all aggregation functions have an na.rm argument which removes the missing values prior to computation:"
    1. Means, counts, and sum
        - counts: n(), which takes no arguments, and returns the size of the current group. 
            - talk about n() vs. count() function
          - Counts and proportions of logical values: sum(x > 10), mean(y == 0). When used with numeric functions, TRUE is converted to 1 and FALSE to 0. This makes sum() and mean() very useful: sum(x) gives the number of TRUEs in x, and mean(x) gives the proportion.            
    1. Other summary functions [5.6.4]
        - measures of position e.g., first(x) x[1]
            - "Measures of position: first(x), nth(x, 2), last(x). These work similarly to x[1], x[2], and x[length(x)] but let you set a default value if that position does not exist (i.e. you’re trying to get the 3rd element from a group that only has two elements). For example, we can find the first and last departure for each day:"
    1. combining processing across obs with filtering
    1. grouping by multiple variables [I haven't re-read this section of wickham yet]
    1. appears that you can skip 5.7 grouped/mutates and filters
    

### Reading [after lecture]

- Wickham 5.6 Grouped summaries with summarise()
- Wickham 5.7 Grouped mutates (and filters)


### Data sources

- decision
    - start with df_event
    - then do some stuff with df_school
- df_event [focus: how characteristics of visited places [and number of visits] differ by group]
    - one obs per university*recruiting_event
    - potential group_by vars
        - university
        - event type
        - state
        - zip-code
        - in-state vs. out-of-state visits
    - potential things to calculate using summarize() and group_by()
        - number of visits by event_type
        - number of visits in each by_group [in_stae vs. out-of-state, public vs. private]
        - mean income for in-state vs. out-of-state visits
- df_school [focus: how characteristics of visited places differ from non-visited places]
    - one obs per high school [both visted and non-visited]
    - potential group_by vars
        - visited vs. non-visited schools
        - in-state vs. out-of-state
        - public vs. private
        - state
    - potential things to calculate using summarize() and group_by()
        - mean enrollment at visited schools vs. non-visited [and state]
        - mean income at visited vs. non-visited 
        - number of visited, number of non-visited
        - mean race at visited vs. non-visited schools
        - academic achievement at visited vs. non-visited
        
- wwlist [not that many things to calculate besides counts]
    - one obs per prospect
    - potential group_by vars
        - state
        - high school
        - zip code
        - gender
        - race
    - potential things to calculate using summarize() and group_by()
        - number of prospects purchased by:
            - state, high school, zip-code, country

### Problem set ideas

### What covered in Stata data mgt course

- Lecture 8: processing across observations, part 1
    - processing across observations using egen command
        - egen to count number of obs in a group; to add all obs in a group for a variable
        - going through some of the sub-commands for egen; count(var) total(var) mean(var)
        - combine processing across obs w/ bysort and egen
    - processing across obs by combining bysort with  _variables
        - introduce _n _N
        - introduce sum() function
    - collapsing obs using _variables
        - bysort id: keep if n== N
        - Collapsing obs using variables, then merging
- Lecture 9: processing across observations, part 2 [lots of student exercises]
    - Processing across obs using _variables
        - table of _variables. column 1= _variable (e.g., _n, _n-1, 1, 2, _N); column 2=meaning of _var
        - calculations within subgroups using _vars
        - various student exercises
    - Filling down obs using _variables
        - filling down using _vars and doing same thing using egen
        - filling down to create imputation vars
    - time series operators for lag and lead obs

### What covered in Christenson class

- lecture 5 [manipulating data frames, 1]
    - transform data
        - mutate to create new variables [using the pipe]
        - group_by 
            - identifies potential groups in stop-and-frisk data
            - group_by example: is an individual above or below the average age in their borough
        - summarize (aggregate and collapse)
    - presenting summary statistics
        - creating tables
            - using summarize() function
        - plot and aggregate data

## Class X. Survey data and Exploratory data analysis [for data quality]

### Big topics

  - read in survey data from _dta format
  - explaining labelled package
  - difference between class=labelled vs. class=factors
  - EDA for data quality [focus on what commands to use]
  - Rules for investigating data, creating variables, checking variables
      - How to be a good RA/researcher  
  - Dealing with skip patterns in survey data
  - Brain-storming how to attack create_gpa assignment

### to do [8/29/2018]

  - make slides for reading in data from other formats/labelled package [wait until you hear back from Crystal?]
      - slides for labelled package; difference between class=labelled vs. class=factors
  - Go through steps in EDA for data quality
      - first, go through all the different checks; 
      - second, rules for investigating and creating variables
          - focus on missing values for input variables
          - do some examples where analysis variable has only one input variable [and you can do simple recode]
  - skip patterns: 
      - make slides for rules/explanations
      - make slides for example
  - Brain-storming how to attack the create_gpa assignment
      - you walk them through EDA to investigate data
      - they brain-storm about how to attack the problem
  

### to do [8/28/2018]

- create hsls dataset: [use layout file; try to find survey questionnaire for S4]
    - has variables that are good candidates for skip-patterns
    - has both quantitative and categorical variables that are good candidates for one-way and two-way stats as discussed from Ben Skinner
    - make sure you can tabulate between universe indicators for s4 and the s4 ever attend PSE type questions
- make sure that task to create NLS course-level data can be done
- make sure you can recode nls variables (crscred=999) using mutate
- start making lecture



### Learning objectives


### Order of lecture

  - EDA for data quality [focus on what commands to use], the tidyverse way [ignore Base R]
      - Investigate objects
      - investigate variable labels/value labels
      - summary stats for continuous vars
      - summary stats for vars w/ discrete values
      - two-way table when both vars have discrete values
  
  
### Data sources for lecture

- one of the recruiting datasets for basics of EDA for data quality analysis?
- maybe use NLS data for everything?
- NLS dataset for
    - skip patterns
    - brain_storming how to tackle problem set

### Problem set ideas

- create GPA from NLS data

### What Ben skinner covers

- EDA 1
    - reading in data from Stata using read_dta
    - labels
        - variable labels
        - value labels
    - summary statistics for continuous variables
        - Base R
            - mean() and sd() functions…
        - tidyverse
            - summarise_at()
    - One-way Discrete/categorical variables
        - "as_factor()"
        - base R
            - table() function
        - tidyverse
            - using count() to create a table; 
                - benefit is that it automatically includes NAs
    - Two-way table
        - base R
            - table(as_factor(df$bypared), as_factor(df$bysex))
        - tidyverse
            - 
            - df %>% group_by(bysex) %>% count(bypared) %>% as_factor()
            - to have one variable as columns and one variable as rows
                - df %>% group_by(bysex) %>% count(bypared) %>% as_factor() %>% spread(bysex, n)
    - conditional mean [good for categorical by continuous]
        - tidyverse
            - mean of continuous var for each value of categorical
                - df %>% group_by(bypared) %>% summarise_at(.vars = vars(bynels2m), .funs = funs(mean, .args = list(na.rm = TRUE))) %>% as_factor()            
            - mean of continuous var for each value of categorical by categorical
            - use "spread" to make it look like published table
            
        
    
    

### What covered in Stata data mgt course

### Reading [after lecture]



## Class X. tidying/reshaping data

## Class X. acquiring data

## Class X. relational data

## Class X. functions

## Class X. iteration
